# version: '3.8'

# services:
#   db:
#     image: mysql

#     volumes:
#       - ./db-init:/docker-entrypoint-initdb.d
#       - mysql_data:/var/lib/mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: "123"
#       MYSQL_DATABASE: world
#     ports:
#       - "3306:3306"

#   web:
#     build: .
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db
#     environment:
#       MYSQL_HOST: db
#       MYSQL_USER: root
#       MYSQL_PASSWORD: "123"
#       MYSQL_DB: world
#       MYSQL_PORT: 3306
# volumes:
#   mysql_data:



version: '3.8'

services:
  db:
    image: mysql
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    env_file: 
      - .env.db
    ports:
      - "3306:3306"

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env.web

volumes:
  mysql_data:
